<a href="https://colab.research.google.com/github/Vinit-Changawala/Binning-Methods-Using-Python/blob/main/Binning_methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math

dataset = [2, 5, 4, 12, 16, 3, 0, 5, 1, 2, 3, 8, 10, 9, 6, 4]
m=0

b=np.sort(dataset)

bin=np.zeros((4,4))
bin1=np.zeros((4,4))
bin2=np.zeros((4,4))
bin3=np.zeros((4,4))

for i in range (0,16,4):
  k=int(i/4)
  for j in range(4):
    bin[k,j]=b[m];m=m+1
print("Equal Bins: \n",bin)

for i in range (0,16,4):
  k=int(i/4)
  mean=(b[i] + b[i+1] + b[i+2] + b[i+3])/4
  for j in range(4):
    bin1[k,j]=mean
print("Bin Mean: \n",bin1)

for i in range (0,16,4):
  k=int(i/4)
  for j in range (4):
    if (b[i+j]-b[i]) < (b[i+3]-b[i+j]):
      bin2[k,j]=b[i]
    else:
      bin2[k,j]=b[i+3]  
print("Bin Boundaries: \n",bin2)

for i in range (0,16,4):
  k=int(i/4)
  for j in range (4):
    bin3[k,j]=(b[i+1] + b[i+2])/2
print("Bin Median: \n",bin3)

Equal Bins: 
 [[ 0.  1.  2.  2.]
 [ 3.  3.  4.  4.]
 [ 5.  5.  6.  8.]
 [ 9. 10. 12. 16.]]
Bin Mean: 
 [[ 1.25  1.25  1.25  1.25]
 [ 3.5   3.5   3.5   3.5 ]
 [ 6.    6.    6.    6.  ]
 [11.75 11.75 11.75 11.75]]
Bin Boundaries: 
 [[ 0.  2.  2.  2.]
 [ 3.  3.  4.  4.]
 [ 5.  5.  5.  8.]
 [ 9.  9.  9. 16.]]
Bin Median: 
 [[ 1.5  1.5  1.5  1.5]
 [ 3.5  3.5  3.5  3.5]
 [ 5.5  5.5  5.5  5.5]
 [11.  11.  11.  11. ]]
